version: '3.9'

networks:
  api-network:
    driver: bridge

services:
  api:
    build: .
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/home/api
    ports:
      - 3000:3000
    depends_on:
      - postgres-api
    environment:
      DB_HOST: postgres-api
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASSWORD}
      DB_DATABASE: ${POSTGRESQL_DATABASE}
    networks:
      - api-network

  postgres-api:
    image: postgres:latest
    container_name: postgres-api
    environment:
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - api-network