networks:
  webnet:
    external: true

services:
  api:
    build: .
    command: npm start
    container_name: api
    env_file:
      - .env
    volumes:
      - .:/home/api
    ports:
      - 3000:3000
    depends_on:
      - postgres-api
    networks:
      - webnet

  postgres-api:
    image: postgres:latest
    container_name: postgres-api
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - webnet
